# Generated by Django 3.2 on 2021-05-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210518_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='optional_notes',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
