# Generated by Django 3.2 on 2021-05-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(),
        ),
    ]
