# Generated by Django 3.2 on 2021-05-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210419_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
