# Generated by Django 3.2 on 2021-05-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
    ]
